-- ============================================================
-- Scriptura — full catalogue resync, generated from ui_kits/scriptura/data.js
-- Run once in Supabase → SQL editor. Safe to re-run (idempotent).
--
-- Replaces the content rows (languages / units / characters / vowels) for
-- every language with exactly what the app ships:
--   • Tamil in Hindi-grid order (Ka · Ca · Ṭa · Ta · Pa · Ra groups + Grantha)
--   • Sinhala and the full Hindi chart
--   • unit.slots   — grid positions for honest gaps on the practice sheet
--   • unit.concept — read-once concept cards (Tamil, Burmese stacking, kana dakuten)
--   • no_vowel_sign — letters the Word Builder must skip
-- Progress (scriptura_app_sheet_stats) is keyed by language + char_index and
-- is NOT touched.
-- Supersedes scriptura_app_fix_tamil_hindi.sql and scriptura_app_add_sinhala.sql.
-- ============================================================

begin;

alter table scriptura_app_units      add column if not exists slots   jsonb;
alter table scriptura_app_units      add column if not exists concept jsonb;
alter table scriptura_app_characters add column if not exists no_vowel_sign boolean default false;

-- ---------- Burmese (33 characters, 6 units) ----------
insert into scriptura_app_languages (id,name,native,grp,font,sort) values ('burmese','Burmese','မြန်မာ','Southeast Asian','var(--font-burmese)',0) on conflict (id) do update set name=excluded.name, native=excluded.native, grp=excluded.grp, font=excluded.font, sort=excluded.sort;
delete from scriptura_app_characters where language_id='burmese';
delete from scriptura_app_vowels where language_id='burmese';
delete from scriptura_app_units where language_id='burmese';
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('burmese_ka','burmese','Ka group','Velar · ကဝဂ်','practice',0,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('burmese_sa','burmese','Sa group','Palatal · စဝဂ်','quiz',1,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('burmese_tta','burmese','Ta group','Retroflex · ဋဝဂ်','sheet',2,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('burmese_ta','burmese','Ta group','Dental · တဝဂ်','review',3,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('burmese_pa','burmese','Pa group','Labial · ပဝဂ်','indic',4,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('burmese_misc','burmese','Miscellaneous','အမျိုးမျိုး','cjk',5,NULL,'{"id":"burmese-stacking","glyph":"န္တ","title":"Letters that stack","blurb":"In some words — mostly from Pali and Sanskrit — one consonant is tucked underneath another instead of being written after it.","note":"Read once before the last consonant group","positions":[{"id":"nta","tab":"န + တ","sound":"n · d","ipa":"","rule":"The top letter closes the syllable before it (as if it had ်); the bottom one starts the next.","parts":[{"t":"မ"},{"t":"န္တ","hi":1},{"t":"လေး"}],"roman":[{"t":"ma"},{"t":"nda","hi":1},{"t":"lay"}],"mean":"Mandalay"},{"id":"dda","tab":"ဒ + ဓ","sound":"k · d","ipa":"","rule":"Stacks usually pair letters from the same row of the grid — here both are dentals. The top one closes as a stop.","parts":[{"t":"ဗု"},{"t":"ဒ္ဓ","hi":1}],"roman":[{"t":"bou"},{"t":"k-da","hi":1}],"mean":"Buddha"},{"id":"ssa","tab":"စ + စ","sound":"t · s","ipa":"","rule":"A letter can also stack on itself: the top copy closes the syllable, the bottom one opens the next.","parts":[{"t":"ပ"},{"t":"စ္စ","hi":1},{"t":"ည်း"}],"roman":[{"t":"pyi"},{"t":"t-s","hi":1},{"t":"i"}],"mean":"thing, belongings"}],"contrast":{"from":{"text":"န် + တ","font":"var(--font-burmese)","label":"written in a row"},"to":{"text":"န္တ","label":"stacked"},"note":"Same sounds either way — stacking drops the ် and moves the second letter underneath. Read top, then bottom."}}'::jsonb);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ka',0,'က','ka','ကကြီး','big ka','क',0,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ka',1,'ခ','kha','ခကွေး','curved kha','ख',1,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ka',2,'ဂ','ga','ဂငယ်','small ga','ग',2,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ka',3,'ဃ','gha','ဃကြီး','big ga','घ',3,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ka',4,'င','nga','င','nga','ङ',4,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_sa',5,'စ','sa','စလုံး','round sa','च',5,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_sa',6,'ဆ','hsa','ဆလိမ်','twisted hsa','छ',6,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_sa',7,'ဇ','za','ဇကွဲ','split za','ज',7,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_sa',8,'ဈ','jha','ဈမျဉ်းဆွဲ','lined za','झ',8,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_sa',9,'ည','nya','ညကြီး','big nya','ञ',9,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_tta',10,'ဋ','ta','ဋသန်လျင်းချိတ်','hooked ta','ट',10,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_tta',11,'ဌ','hta','ဌဝမ်းဘဲ','duck-belly hta','ठ',11,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_tta',12,'ဍ','da','ဍရင်ကောက်','curved-chest da','ड',12,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_tta',13,'ဎ','dha','ဎရေမှုတ်','water-blown dha','ढ',13,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_tta',14,'ဏ','na','ဏကြီး','big na','ण',14,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ta',15,'တ','ta','တဝမ်းပူ','pot-belly ta','त',15,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ta',16,'ထ','hta','ထဆင်ထူး','elephant-fetter hta','थ',16,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ta',17,'ဒ','da','ဒထွေး','forked da','द',17,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ta',18,'ဓ','dha','ဓအောက်ခြိုက်','dented-below dha','ध',18,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_ta',19,'န','na','နငယ်','small na','न',19,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_pa',20,'ပ','pa','ပစောက်','deep pa','प',20,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_pa',21,'ဖ','pha','ဖဦးထုပ်','capped pha','फ',21,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_pa',22,'ဗ','ba','ဗထက်ခြိုက်','dented-above ba','ब',22,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_pa',23,'ဘ','bha','ဘကုန်း','humped bha','भ',23,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_pa',24,'မ','ma','မ','ma','म',24,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_misc',25,'ယ','ya','ယပက်လက်','supine ya','य',25,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_misc',26,'ရ','ya','ရကောက်','curved ya','र',26,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_misc',27,'လ','la','လ','la','ल',27,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_misc',28,'ဝ','wa','ဝ','wa','व',28,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_misc',29,'သ','tha','သ','tha','स',29,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_misc',30,'ဟ','ha','ဟ','ha','ह',30,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_misc',31,'ဠ','la','ဠကြီး','big la','ळ',31,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('burmese','burmese_misc',32,'အ','a','အ','a','अ',32,false);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('burmese','ာ','ā',NULL,0);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('burmese','ိ','i',NULL,1);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('burmese','ီ','ī',NULL,2);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('burmese','ု','u',NULL,3);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('burmese','ူ','ū',NULL,4);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('burmese','ေ','e',NULL,5);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('burmese','ဲ','ai',NULL,6);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('burmese','ော','aw',NULL,7);

-- ---------- Hindi (36 characters, 6 units) ----------
insert into scriptura_app_languages (id,name,native,grp,font,sort) values ('hindi','Hindi','हिन्दी','South Asian','var(--font-devanagari)',1) on conflict (id) do update set name=excluded.name, native=excluded.native, grp=excluded.grp, font=excluded.font, sort=excluded.sort;
delete from scriptura_app_characters where language_id='hindi';
delete from scriptura_app_vowels where language_id='hindi';
delete from scriptura_app_units where language_id='hindi';
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hindi_ka','hindi','Ka group','Velar','practice',0,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hindi_sa','hindi','Sa group','Palatal','quiz',1,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hindi_tta','hindi','Ta group','Retroflex','sheet',2,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hindi_ta','hindi','Ta group','Dental','review',3,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hindi_pa','hindi','Pa group','Labial','indic',4,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hindi_misc','hindi','Miscellaneous','Semivowels & sibilants','cjk',5,NULL,NULL);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ka',0,'क','ka','ka','','',0,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ka',1,'ख','kha','kha','','',1,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ka',2,'ग','ga','ga','','',2,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ka',3,'घ','gha','gha','','',3,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ka',4,'ङ','ṅa','ṅa','','',4,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_sa',5,'च','ca','ca','','',5,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_sa',6,'छ','cha','cha','','',6,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_sa',7,'ज','ja','ja','','',7,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_sa',8,'झ','jha','jha','','',8,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_sa',9,'ञ','ña','ña','','',9,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_tta',10,'ट','ṭa','ṭa','','',10,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_tta',11,'ठ','ṭha','ṭha','','',11,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_tta',12,'ड','ḍa','ḍa','','',12,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_tta',13,'ढ','ḍha','ḍha','','',13,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_tta',14,'ण','ṇa','ṇa','','',14,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ta',15,'त','ta','ta','','',15,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ta',16,'थ','tha','tha','','',16,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ta',17,'द','da','da','','',17,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ta',18,'ध','dha','dha','','',18,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_ta',19,'न','na','na','','',19,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_pa',20,'प','pa','pa','','',20,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_pa',21,'फ','pha','pha','','',21,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_pa',22,'ब','ba','ba','','',22,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_pa',23,'भ','bha','bha','','',23,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_pa',24,'म','ma','ma','','',24,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',25,'य','ya','ya','','',25,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',26,'र','ra','ra','','',26,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',27,'ल','la','la','','',27,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',28,'व','va','va','','',28,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',29,'श','śa','śa','','',29,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',30,'ष','ṣa','ṣa','','',30,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',31,'स','sa','sa','','',31,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',32,'ह','ha','ha','','',32,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',33,'ळ','ḷa','ḷa','','',33,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',34,'क्ष','kṣa','kṣa','','',34,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hindi','hindi_misc',35,'ज्ञ','jña','jña','','',35,false);

-- ---------- Telugu (35 characters, 6 units) ----------
insert into scriptura_app_languages (id,name,native,grp,font,sort) values ('telugu','Telugu','తెలుగు','South Asian','var(--font-telugu)',2) on conflict (id) do update set name=excluded.name, native=excluded.native, grp=excluded.grp, font=excluded.font, sort=excluded.sort;
delete from scriptura_app_characters where language_id='telugu';
delete from scriptura_app_vowels where language_id='telugu';
delete from scriptura_app_units where language_id='telugu';
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('telugu_ka','telugu','Ka group','Velar','practice',0,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('telugu_sa','telugu','Sa group','Palatal','quiz',1,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('telugu_tta','telugu','Ta group','Retroflex','sheet',2,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('telugu_ta','telugu','Ta group','Dental','review',3,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('telugu_pa','telugu','Pa group','Labial','indic',4,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('telugu_misc','telugu','Miscellaneous','Semivowels & sibilants','cjk',5,NULL,NULL);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ka',0,'క','ka','ka','','',0,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ka',1,'ఖ','kha','kha','','',1,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ka',2,'గ','ga','ga','','',2,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ka',3,'ఘ','gha','gha','','',3,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ka',4,'ఙ','ṅa','ṅa','','',4,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_sa',5,'చ','ca','ca','','',5,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_sa',6,'ఛ','cha','cha','','',6,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_sa',7,'జ','ja','ja','','',7,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_sa',8,'ఝ','jha','jha','','',8,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_sa',9,'ఞ','ña','ña','','',9,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_tta',10,'ట','ṭa','ṭa','','',10,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_tta',11,'ఠ','ṭha','ṭha','','',11,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_tta',12,'డ','ḍa','ḍa','','',12,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_tta',13,'ఢ','ḍha','ḍha','','',13,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_tta',14,'ణ','ṇa','ṇa','','',14,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ta',15,'త','ta','ta','','',15,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ta',16,'థ','tha','tha','','',16,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ta',17,'ద','da','da','','',17,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ta',18,'ధ','dha','dha','','',18,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_ta',19,'న','na','na','','',19,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_pa',20,'ప','pa','pa','','',20,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_pa',21,'ఫ','pha','pha','','',21,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_pa',22,'బ','ba','ba','','',22,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_pa',23,'భ','bha','bha','','',23,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_pa',24,'మ','ma','ma','','',24,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',25,'య','ya','ya','','',25,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',26,'ర','ra','ra','','',26,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',27,'ల','la','la','','',27,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',28,'వ','va','va','','',28,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',29,'శ','śa','śa','','',29,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',30,'ష','ṣa','ṣa','','',30,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',31,'స','sa','sa','','',31,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',32,'హ','ha','ha','','',32,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',33,'ళ','ḷa','ḷa','','',33,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('telugu','telugu_misc',34,'ఱ','ṟa','ṟa','','',34,false);

-- ---------- Sinhala (35 characters, 6 units) ----------
insert into scriptura_app_languages (id,name,native,grp,font,sort) values ('sinhala','Sinhala','සිංහල','South Asian','var(--font-sinhala)',3) on conflict (id) do update set name=excluded.name, native=excluded.native, grp=excluded.grp, font=excluded.font, sort=excluded.sort;
delete from scriptura_app_characters where language_id='sinhala';
delete from scriptura_app_vowels where language_id='sinhala';
delete from scriptura_app_units where language_id='sinhala';
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('sinhala_ka','sinhala','Ka group','Velar','practice',0,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('sinhala_sa','sinhala','Sa group','Palatal','quiz',1,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('sinhala_tta','sinhala','Ta group','Retroflex','sheet',2,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('sinhala_ta','sinhala','Ta group','Dental','review',3,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('sinhala_pa','sinhala','Pa group','Labial','indic',4,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('sinhala_misc','sinhala','Miscellaneous','Semivowels & sibilants','cjk',5,NULL,NULL);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ka',0,'ක','ka','ka','','',0,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ka',1,'ඛ','kha','kha','','',1,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ka',2,'ග','ga','ga','','',2,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ka',3,'ඝ','gha','gha','','',3,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ka',4,'ඞ','ṅa','ṅa','','',4,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_sa',5,'ච','ca','ca','','',5,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_sa',6,'ඡ','cha','cha','','',6,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_sa',7,'ජ','ja','ja','','',7,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_sa',8,'ඣ','jha','jha','','',8,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_sa',9,'ඤ','ña','ña','','',9,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_tta',10,'ට','ṭa','ṭa','','',10,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_tta',11,'ඨ','ṭha','ṭha','','',11,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_tta',12,'ඩ','ḍa','ḍa','','',12,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_tta',13,'ඪ','ḍha','ḍha','','',13,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_tta',14,'ණ','ṇa','ṇa','','',14,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ta',15,'ත','ta','ta','','',15,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ta',16,'ථ','tha','tha','','',16,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ta',17,'ද','da','da','','',17,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ta',18,'ධ','dha','dha','','',18,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_ta',19,'න','na','na','','',19,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_pa',20,'ප','pa','pa','','',20,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_pa',21,'ඵ','pha','pha','','',21,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_pa',22,'බ','ba','ba','','',22,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_pa',23,'භ','bha','bha','','',23,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_pa',24,'ම','ma','ma','','',24,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',25,'ය','ya','ya','','',25,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',26,'ර','ra','ra','','',26,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',27,'ල','la','la','','',27,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',28,'ව','va','va','','',28,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',29,'ශ','śa','śa','','',29,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',30,'ෂ','ṣa','ṣa','','',30,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',31,'ස','sa','sa','','',31,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',32,'හ','ha','ha','','',32,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',33,'ළ','ḷa','ḷa','','',33,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('sinhala','sinhala_misc',34,'ෆ','fa','fa','','',34,false);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('sinhala','ා','ā',NULL,0);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('sinhala','ි','i',NULL,1);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('sinhala','ී','ī',NULL,2);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('sinhala','ු','u',NULL,3);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('sinhala','ූ','ū',NULL,4);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('sinhala','ෙ','e',NULL,5);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('sinhala','ේ','ē',NULL,6);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('sinhala','ො','o',NULL,7);

-- ---------- Tamil (37 characters, 9 units) ----------
insert into scriptura_app_languages (id,name,native,grp,font,sort) values ('tamil','Tamil','தமிழ்','South Asian','var(--font-tamil)',4) on conflict (id) do update set name=excluded.name, native=excluded.native, grp=excluded.grp, font=excluded.font, sort=excluded.sort;
delete from scriptura_app_characters where language_id='tamil';
delete from scriptura_app_vowels where language_id='tamil';
delete from scriptura_app_units where language_id='tamil';
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('tamil_uyir','tamil','Uyir','Vowels · உயிர்','practice',0,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('tamil_ka','tamil','Ka group','Velar · க ங','quiz',1,'[0,null,null,null,1]'::jsonb,'{"id":"tamil-ka-allophony","title":"One letter, two sounds","blurb":"Tamil doesn’t spell the difference between k and g — where the letter sits in the word decides it.","note":"Read once before the Ka group","glyph":"க","positions":[{"id":"initial","tab":"Start of word","sound":"k","ipa":"/k/","rule":"Word-initial க is always a hard k.","parts":[{"t":"க","hi":1},{"t":"டல்"}],"roman":[{"t":"ka","hi":1},{"t":"dal"}],"mean":"sea"},{"id":"double","tab":"Doubled","sound":"k","ipa":"/k/","rule":"Doubled க்க stays hard — this is how Tamil writes a real k between vowels.","parts":[{"t":"ப"},{"t":"க்க","hi":1},{"t":"ம்"}],"roman":[{"t":"pa"},{"t":"kka","hi":1},{"t":"m"}],"mean":"page, side"},{"id":"medial","tab":"Between vowels","sound":"g","ipa":"/ɣ~g/","rule":"A single க between two vowels softens to g — in some words closer to h.","parts":[{"t":"ம"},{"t":"க","hi":1},{"t":"ன்"}],"roman":[{"t":"ma"},{"t":"ga","hi":1},{"t":"n"}],"mean":"son"},{"id":"nasal","tab":"After ங","sound":"g","ipa":"/ŋg/","rule":"After its own nasal ங, க voices to g.","parts":[{"t":"தங்"},{"t":"க","hi":1},{"t":"ம்"}],"roman":[{"t":"tha"},{"t":"nga","hi":1},{"t":"m"}],"mean":"gold"}],"contrast":{"from":{"text":"क ख ग घ","font":"var(--font-devanagari)","label":"Hindi · 4 letters"},"to":{"text":"க","label":"Tamil · 1 letter"},"note":"Tamil has no aspirates and no separate voiced stops, so there was never a kha or gha to spell. The same holds for ச · ட · த · ப."}}'::jsonb);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('tamil_ca','tamil','Ca group','Palatal · ச ஞ','sheet',2,'[0,null,null,null,1]'::jsonb,'{"id":"tamil-ca-allophony","glyph":"ச","title":"ச — one letter, two sounds","blurb":"Same rule as க: where ச sits in the word decides whether it is ch or s / j.","note":"Read once before the Ca group","positions":[{"id":"initial","tab":"Start of word","sound":"s","ipa":"/s~tʃ/","rule":"Word-initial ச is usually s in speech (ch in careful reading).","parts":[{"t":"ச","hi":1},{"t":"ட்டை"}],"roman":[{"t":"sa","hi":1},{"t":"ṭṭai"}],"mean":"shirt"},{"id":"double","tab":"Doubled","sound":"ch","ipa":"/ttʃ/","rule":"Doubled ச்ச is always a hard ch.","parts":[{"t":"ப"},{"t":"ச்சை","hi":1}],"roman":[{"t":"pa"},{"t":"cc","hi":1},{"t":"ai"}],"mean":"green"},{"id":"medial","tab":"Between vowels","sound":"s","ipa":"/s/","rule":"A single ச between vowels is s.","parts":[{"t":"ப"},{"t":"சு","hi":1}],"roman":[{"t":"pa"},{"t":"su","hi":1}],"mean":"cow"},{"id":"nasal","tab":"After ஞ","sound":"j","ipa":"/ɲdʒ/","rule":"After its own nasal ஞ, ச voices to j.","parts":[{"t":"பஞ்"},{"t":"சு","hi":1}],"roman":[{"t":"pañ"},{"t":"ju","hi":1}],"mean":"cotton"}],"contrast":{"from":{"text":"च छ ज झ","font":"var(--font-devanagari)","label":"Hindi · 4 letters"},"to":{"text":"ச","label":"Tamil · 1 letter"},"note":"No aspirates, no separate voiced letter — one ச covers all four Hindi sounds."}}'::jsonb);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('tamil_tta','tamil','Ta group','Retroflex · ட ண','review',3,'[0,null,null,null,1]'::jsonb,'{"id":"tamil-tta-allophony","glyph":"ட","title":"ட — one letter, two sounds","blurb":"Same rule as க: where ட sits in the word decides whether it is ṭ or ḍ.","note":"Read once before the retroflex Ta group","positions":[{"id":"initial","tab":"Start of word","sound":"ṭ","ipa":"/ʈ/","rule":"Native Tamil words never start with ட — you only see it first in loanwords.","parts":[{"t":"ட","hi":1},{"t":"ம்ளர்"}],"roman":[{"t":"ṭa","hi":1},{"t":"mḷar"}],"mean":"tumbler (loanword)"},{"id":"double","tab":"Doubled","sound":"ṭṭ","ipa":"/ʈʈ/","rule":"Doubled ட்ட stays hard.","parts":[{"t":"ப"},{"t":"ட்ட","hi":1},{"t":"ம்"}],"roman":[{"t":"pa"},{"t":"ṭṭa","hi":1},{"t":"m"}],"mean":"kite; title"},{"id":"medial","tab":"Between vowels","sound":"ḍ","ipa":"/ɖ~ɽ/","rule":"A single ட between vowels softens to ḍ, often a quick flap.","parts":[{"t":"வீ"},{"t":"டு","hi":1}],"roman":[{"t":"vī"},{"t":"ḍu","hi":1}],"mean":"house"},{"id":"nasal","tab":"After ண","sound":"ḍ","ipa":"/ɳɖ/","rule":"After its own nasal ண, ட voices to ḍ.","parts":[{"t":"வண்"},{"t":"டி","hi":1}],"roman":[{"t":"vaṇ"},{"t":"ḍi","hi":1}],"mean":"cart"}],"contrast":{"from":{"text":"ट ठ ड ढ","font":"var(--font-devanagari)","label":"Hindi · 4 letters"},"to":{"text":"ட","label":"Tamil · 1 letter"},"note":"Tongue curled back for all of them — Tamil just doesn’t spell voicing."}}'::jsonb);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('tamil_ta','tamil','Ta group','Dental · த ந','indic',4,'[0,null,null,null,1]'::jsonb,'{"id":"tamil-ta-allophony","glyph":"த","title":"த — one letter, two sounds","blurb":"Same rule as க: where த sits in the word decides whether it is t or d.","note":"Read once before the dental Ta group","positions":[{"id":"initial","tab":"Start of word","sound":"t","ipa":"/t̪/","rule":"Word-initial த is a hard dental t — tongue on the teeth.","parts":[{"t":"த","hi":1},{"t":"மிழ்"}],"roman":[{"t":"ta","hi":1},{"t":"miḻ"}],"mean":"Tamil"},{"id":"double","tab":"Doubled","sound":"tt","ipa":"/t̪t̪/","rule":"Doubled த்த stays hard.","parts":[{"t":"ப"},{"t":"த்து","hi":1}],"roman":[{"t":"pa"},{"t":"ttu","hi":1}],"mean":"ten"},{"id":"medial","tab":"Between vowels","sound":"d","ipa":"/d̪~ð/","rule":"A single த between vowels softens to d, close to the th in “this”.","parts":[{"t":"பா"},{"t":"த","hi":1},{"t":"ம்"}],"roman":[{"t":"pā"},{"t":"da","hi":1},{"t":"m"}],"mean":"foot"},{"id":"nasal","tab":"After ந","sound":"d","ipa":"/n̪d̪/","rule":"After its own nasal ந, த voices to d.","parts":[{"t":"பந்"},{"t":"து","hi":1}],"roman":[{"t":"pan"},{"t":"du","hi":1}],"mean":"ball"}],"contrast":{"from":{"text":"त थ द ध","font":"var(--font-devanagari)","label":"Hindi · 4 letters"},"to":{"text":"த","label":"Tamil · 1 letter"},"note":"Keep it dental: த is a different letter from the retroflex ட you just learned."}}'::jsonb);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('tamil_pa','tamil','Pa group','Labial · ப ம','cjk',5,'[0,null,null,null,1]'::jsonb,'{"id":"tamil-pa-allophony","glyph":"ப","title":"ப — one letter, two sounds","blurb":"Same rule as க: where ப sits in the word decides whether it is p or b.","note":"Read once before the Pa group","positions":[{"id":"initial","tab":"Start of word","sound":"p","ipa":"/p/","rule":"Word-initial ப is a hard p.","parts":[{"t":"ப","hi":1},{"t":"ல்"}],"roman":[{"t":"pa","hi":1},{"t":"l"}],"mean":"tooth"},{"id":"double","tab":"Doubled","sound":"pp","ipa":"/pp/","rule":"Doubled ப்ப stays hard.","parts":[{"t":"அ"},{"t":"ப்பா","hi":1}],"roman":[{"t":"a"},{"t":"ppā","hi":1}],"mean":"father"},{"id":"medial","tab":"Between vowels","sound":"b","ipa":"/b~β/","rule":"A single ப between vowels softens to b, lips barely touching.","parts":[{"t":"கோ"},{"t":"ப","hi":1},{"t":"ம்"}],"roman":[{"t":"kō"},{"t":"ba","hi":1},{"t":"m"}],"mean":"anger"},{"id":"nasal","tab":"After ம","sound":"b","ipa":"/mb/","rule":"After its own nasal ம, ப voices to b.","parts":[{"t":"பாம்"},{"t":"பு","hi":1}],"roman":[{"t":"pām"},{"t":"bu","hi":1}],"mean":"snake"}],"contrast":{"from":{"text":"प फ ब भ","font":"var(--font-devanagari)","label":"Hindi · 4 letters"},"to":{"text":"ப","label":"Tamil · 1 letter"},"note":"That completes the pattern: க ச ட த ப each stand for a hard and a soft sound."}}'::jsonb);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('tamil_ra','tamil','Ra group','Alveolar · ற ன','practice',6,'[0,null,null,null,1]'::jsonb,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('tamil_idaiyinam','tamil','Idaiyinam','Semivowels & liquids · இடையினம்','quiz',7,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('tamil_grantha','tamil','Grantha & Āytam','Borrowed · கிரந்தம்','indic',8,NULL,NULL);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',0,'அ','a','அ','vowel a','',0,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',1,'ஆ','ā','ஆ','long ā','',1,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',2,'இ','i','இ','i','',2,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',3,'ஈ','ī','ஈ','long ī','',3,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',4,'உ','u','உ','u','',4,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',5,'ஊ','ū','ஊ','long ū','',5,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',6,'எ','e','எ','e','',6,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',7,'ஏ','ē','ஏ','long ē','',7,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',8,'ஐ','ai','ஐ','ai','',8,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',9,'ஒ','o','ஒ','o','',9,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',10,'ஓ','ō','ஓ','long ō','',10,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_uyir',11,'ஔ','au','ஔ','au','',11,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_ka',12,'க','ka','க','ka · ga between vowels','क',12,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_ka',13,'ங','ṅa','ங','nga','ङ',13,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_ca',14,'ச','ca','ச','cha · sa at word start','च',14,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_ca',15,'ஞ','ña','ஞ','nya','ञ',15,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_tta',16,'ட','ṭa','ட','retroflex ta · da between vowels','ट',16,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_tta',17,'ண','ṇa','ண','retroflex na','ण',17,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_ta',18,'த','ta','த','dental ta · dha between vowels','त',18,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_ta',19,'ந','na','ந','dental na','न',19,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_pa',20,'ப','pa','ப','pa · ba between vowels','प',20,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_pa',21,'ம','ma','ம','ma','म',21,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_ra',22,'ற','ṟa','ற','trilled ra · tra when doubled','',22,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_ra',23,'ன','ṉa','ன','alveolar na','',23,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_idaiyinam',24,'ய','ya','ய','ya','य',24,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_idaiyinam',25,'ர','ra','ர','ra','र',25,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_idaiyinam',26,'ல','la','ல','la','ल',26,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_idaiyinam',27,'வ','va','வ','va','व',27,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_idaiyinam',28,'ழ','ḻa','ழ','retroflex zha · unique to Tamil','',28,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_idaiyinam',29,'ள','ḷa','ள','retroflex la','ळ',29,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_grantha',30,'ஃ','ḵ','ஆய்த எழுத்து','āytam · ஃப = f, ஃஜ = z','',30,true);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_grantha',31,'ஜ','ja','ஜ','ja · loanwords only','ज',31,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_grantha',32,'ஷ','ṣa','ஷ','retroflex sha','ष',32,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_grantha',33,'ஸ','sa','ஸ','sibilant sa','स',33,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_grantha',34,'ஹ','ha','ஹ','ha','ह',34,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_grantha',35,'க்ஷ','kṣa','க்ஷ','ksha · ligature','क्ष',35,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('tamil','tamil_grantha',36,'ஸ்ரீ','śrī','ஸ்ரீ','shri · ligature','श्री',36,true);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ா','ā',NULL,0);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ி','i',NULL,1);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ீ','ī',NULL,2);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ு','u',NULL,3);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ூ','ū',NULL,4);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ெ','e',NULL,5);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ே','ē',NULL,6);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ை','ai',NULL,7);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ொ','o',NULL,8);
insert into scriptura_app_vowels (language_id,sign,label,name,sort) values ('tamil','ோ','ō',NULL,9);

-- ---------- Hiragana (46 characters, 10 units) ----------
insert into scriptura_app_languages (id,name,native,grp,font,sort) values ('hiragana','Hiragana','ひらがな','East Asian','var(--font-japanese)',5) on conflict (id) do update set name=excluded.name, native=excluded.native, grp=excluded.grp, font=excluded.font, sort=excluded.sort;
delete from scriptura_app_characters where language_id='hiragana';
delete from scriptura_app_vowels where language_id='hiragana';
delete from scriptura_app_units where language_id='hiragana';
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_vowels','hiragana','Vowels','あ','practice',0,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_k','hiragana','K-row','か','quiz',1,NULL,'{"id":"hiragana-dakuten","glyph":"が","title":"Two small marks, a new sound","blurb":"A tiny ゛ (dakuten) voices the consonant; a tiny ゜ (handakuten), only on the H-row, turns it into p. No new shapes to learn.","note":"Read once before the K-row","positions":[{"id":"g","tab":"か → が","sound":"g","ipa":"/ɡ/","rule":"゛ turns k into g.","parts":[{"t":"が","hi":1},{"t":"っこう"}],"roman":[{"t":"ga","hi":1},{"t":"kkō"}],"mean":"school"},{"id":"z","tab":"さ → ざ","sound":"z","ipa":"/z/","rule":"゛ turns s into z.","parts":[{"t":"ざ","hi":1},{"t":"っし"}],"roman":[{"t":"za","hi":1},{"t":"sshi"}],"mean":"magazine"},{"id":"d","tab":"た → だ","sound":"d","ipa":"/d/","rule":"゛ turns t into d.","parts":[{"t":"だ","hi":1},{"t":"いがく"}],"roman":[{"t":"da","hi":1},{"t":"igaku"}],"mean":"university"},{"id":"b","tab":"は → ば","sound":"b","ipa":"/b/","rule":"゛ on the H-row gives b, not v.","parts":[{"t":"ば","hi":1},{"t":"んごはん"}],"roman":[{"t":"ba","hi":1},{"t":"ngohan"}],"mean":"dinner"},{"id":"p","tab":"は → ぱ","sound":"p","ipa":"/p/","rule":"゜ — the small circle — only goes on the H-row, and gives p.","parts":[{"t":"ぱ","hi":1},{"t":"ん"}],"roman":[{"t":"pa","hi":1},{"t":"n"}],"mean":"bread"}],"contrast":{"from":{"text":"か さ た は","font":"var(--font-japanese)","label":"plain"},"to":{"text":"が ざ だ ば ぱ","label":"marked"},"note":"Five rows you already know give you 25 more sounds for free."}}'::jsonb);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_s','hiragana','S-row','さ','sheet',2,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_t','hiragana','T-row','た','review',3,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_n','hiragana','N-row','な','indic',4,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_h','hiragana','H-row','は','cjk',5,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_m','hiragana','M-row','ま','practice',6,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_y','hiragana','Y-row','や','quiz',7,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_r','hiragana','R-row','ら','sheet',8,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('hiragana_w','hiragana','W-row & N','わ','review',9,NULL,NULL);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_vowels',0,'あ','a','a','','',0,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_vowels',1,'い','i','i','','',1,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_vowels',2,'う','u','u','','',2,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_vowels',3,'え','e','e','','',3,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_vowels',4,'お','o','o','','',4,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_k',5,'か','ka','ka','','',5,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_k',6,'き','ki','ki','','',6,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_k',7,'く','ku','ku','','',7,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_k',8,'け','ke','ke','','',8,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_k',9,'こ','ko','ko','','',9,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_s',10,'さ','sa','sa','','',10,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_s',11,'し','shi','shi','','',11,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_s',12,'す','su','su','','',12,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_s',13,'せ','se','se','','',13,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_s',14,'そ','so','so','','',14,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_t',15,'た','ta','ta','','',15,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_t',16,'ち','chi','chi','','',16,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_t',17,'つ','tsu','tsu','','',17,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_t',18,'て','te','te','','',18,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_t',19,'と','to','to','','',19,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_n',20,'な','na','na','','',20,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_n',21,'に','ni','ni','','',21,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_n',22,'ぬ','nu','nu','','',22,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_n',23,'ね','ne','ne','','',23,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_n',24,'の','no','no','','',24,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_h',25,'は','ha','ha','','',25,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_h',26,'ひ','hi','hi','','',26,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_h',27,'ふ','fu','fu','','',27,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_h',28,'へ','he','he','','',28,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_h',29,'ほ','ho','ho','','',29,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_m',30,'ま','ma','ma','','',30,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_m',31,'み','mi','mi','','',31,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_m',32,'む','mu','mu','','',32,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_m',33,'め','me','me','','',33,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_m',34,'も','mo','mo','','',34,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_y',35,'や','ya','ya','','',35,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_y',36,'ゆ','yu','yu','','',36,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_y',37,'よ','yo','yo','','',37,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_r',38,'ら','ra','ra','','',38,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_r',39,'り','ri','ri','','',39,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_r',40,'る','ru','ru','','',40,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_r',41,'れ','re','re','','',41,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_r',42,'ろ','ro','ro','','',42,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_w',43,'わ','wa','wa','','',43,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_w',44,'を','wo','wo','','',44,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('hiragana','hiragana_w',45,'ん','n','n','','',45,false);

-- ---------- Katakana (46 characters, 10 units) ----------
insert into scriptura_app_languages (id,name,native,grp,font,sort) values ('katakana','Katakana','カタカナ','East Asian','var(--font-japanese)',6) on conflict (id) do update set name=excluded.name, native=excluded.native, grp=excluded.grp, font=excluded.font, sort=excluded.sort;
delete from scriptura_app_characters where language_id='katakana';
delete from scriptura_app_vowels where language_id='katakana';
delete from scriptura_app_units where language_id='katakana';
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_vowels','katakana','Vowels','ア','practice',0,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_k','katakana','K-row','カ','quiz',1,NULL,'{"id":"katakana-dakuten","glyph":"ガ","title":"Two small marks, a new sound","blurb":"A tiny ゛ (dakuten) voices the consonant; a tiny ゜ (handakuten), only on the H-row, turns it into p. No new shapes to learn.","note":"Read once before the K-row","positions":[{"id":"g","tab":"カ → ガ","sound":"g","ipa":"/ɡ/","rule":"゛ turns k into g.","parts":[{"t":"ガ","hi":1},{"t":"ム"}],"roman":[{"t":"ga","hi":1},{"t":"mu"}],"mean":"chewing gum"},{"id":"z","tab":"サ → ザ","sound":"z","ipa":"/z/","rule":"゛ turns s into z.","parts":[{"t":"ゼ","hi":1},{"t":"ロ"}],"roman":[{"t":"ze","hi":1},{"t":"ro"}],"mean":"zero"},{"id":"d","tab":"タ → ダ","sound":"d","ipa":"/d/","rule":"゛ turns t into d.","parts":[{"t":"ド","hi":1},{"t":"ア"}],"roman":[{"t":"do","hi":1},{"t":"a"}],"mean":"door"},{"id":"b","tab":"ハ → バ","sound":"b","ipa":"/b/","rule":"゛ on the H-row gives b, not v.","parts":[{"t":"バ","hi":1},{"t":"ス"}],"roman":[{"t":"ba","hi":1},{"t":"su"}],"mean":"bus"},{"id":"p","tab":"ハ → パ","sound":"p","ipa":"/p/","rule":"゜ — the small circle — only goes on the H-row, and gives p.","parts":[{"t":"パ","hi":1},{"t":"ン"}],"roman":[{"t":"pa","hi":1},{"t":"n"}],"mean":"bread"}],"contrast":{"from":{"text":"カ サ タ ハ","font":"var(--font-japanese)","label":"plain"},"to":{"text":"ガ ザ ダ バ パ","label":"marked"},"note":"Five rows you already know give you 25 more sounds for free."}}'::jsonb);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_s','katakana','S-row','サ','sheet',2,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_t','katakana','T-row','タ','review',3,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_n','katakana','N-row','ナ','indic',4,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_h','katakana','H-row','ハ','cjk',5,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_m','katakana','M-row','マ','practice',6,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_y','katakana','Y-row','ヤ','quiz',7,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_r','katakana','R-row','ラ','sheet',8,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('katakana_w','katakana','W-row & N','ワ','review',9,NULL,NULL);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_vowels',0,'ア','a','a','','',0,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_vowels',1,'イ','i','i','','',1,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_vowels',2,'ウ','u','u','','',2,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_vowels',3,'エ','e','e','','',3,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_vowels',4,'オ','o','o','','',4,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_k',5,'カ','ka','ka','','',5,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_k',6,'キ','ki','ki','','',6,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_k',7,'ク','ku','ku','','',7,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_k',8,'ケ','ke','ke','','',8,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_k',9,'コ','ko','ko','','',9,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_s',10,'サ','sa','sa','','',10,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_s',11,'シ','shi','shi','','',11,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_s',12,'ス','su','su','','',12,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_s',13,'セ','se','se','','',13,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_s',14,'ソ','so','so','','',14,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_t',15,'タ','ta','ta','','',15,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_t',16,'チ','chi','chi','','',16,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_t',17,'ツ','tsu','tsu','','',17,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_t',18,'テ','te','te','','',18,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_t',19,'ト','to','to','','',19,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_n',20,'ナ','na','na','','',20,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_n',21,'ニ','ni','ni','','',21,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_n',22,'ヌ','nu','nu','','',22,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_n',23,'ネ','ne','ne','','',23,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_n',24,'ノ','no','no','','',24,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_h',25,'ハ','ha','ha','','',25,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_h',26,'ヒ','hi','hi','','',26,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_h',27,'フ','fu','fu','','',27,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_h',28,'ヘ','he','he','','',28,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_h',29,'ホ','ho','ho','','',29,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_m',30,'マ','ma','ma','','',30,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_m',31,'ミ','mi','mi','','',31,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_m',32,'ム','mu','mu','','',32,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_m',33,'メ','me','me','','',33,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_m',34,'モ','mo','mo','','',34,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_y',35,'ヤ','ya','ya','','',35,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_y',36,'ユ','yu','yu','','',36,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_y',37,'ヨ','yo','yo','','',37,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_r',38,'ラ','ra','ra','','',38,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_r',39,'リ','ri','ri','','',39,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_r',40,'ル','ru','ru','','',40,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_r',41,'レ','re','re','','',41,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_r',42,'ロ','ro','ro','','',42,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_w',43,'ワ','wa','wa','','',43,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_w',44,'ヲ','wo','wo','','',44,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('katakana','katakana_w',45,'ン','n','n','','',45,false);

-- ---------- Korean (19 characters, 3 units) ----------
insert into scriptura_app_languages (id,name,native,grp,font,sort) values ('korean','Korean','한국어','East Asian','var(--font-korean)',7) on conflict (id) do update set name=excluded.name, native=excluded.native, grp=excluded.grp, font=excluded.font, sort=excluded.sort;
delete from scriptura_app_characters where language_id='korean';
delete from scriptura_app_vowels where language_id='korean';
delete from scriptura_app_units where language_id='korean';
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('korean_basic1','korean','Basic I','ㄱ–ㅅ','practice',0,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('korean_basic2','korean','Basic II','ㅇ–ㅎ','quiz',1,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('korean_tense','korean','Tense','ㄲ–ㅉ','sheet',2,NULL,NULL);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic1',0,'ㄱ','g/k','g/k','','',0,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic1',1,'ㄴ','n','n','','',1,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic1',2,'ㄷ','d/t','d/t','','',2,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic1',3,'ㄹ','r/l','r/l','','',3,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic1',4,'ㅁ','m','m','','',4,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic1',5,'ㅂ','b/p','b/p','','',5,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic1',6,'ㅅ','s','s','','',6,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic2',7,'ㅇ','ng','ng','','',7,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic2',8,'ㅈ','j','j','','',8,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic2',9,'ㅊ','ch','ch','','',9,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic2',10,'ㅋ','k','k','','',10,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic2',11,'ㅌ','t','t','','',11,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic2',12,'ㅍ','p','p','','',12,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_basic2',13,'ㅎ','h','h','','',13,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_tense',14,'ㄲ','kk','kk','','',14,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_tense',15,'ㄸ','tt','tt','','',15,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_tense',16,'ㅃ','pp','pp','','',16,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_tense',17,'ㅆ','ss','ss','','',17,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('korean','korean_tense',18,'ㅉ','jj','jj','','',18,false);

-- ---------- Chinese (20 characters, 2 units) ----------
insert into scriptura_app_languages (id,name,native,grp,font,sort) values ('chinese','Chinese','汉字','East Asian','var(--font-chinese)',8) on conflict (id) do update set name=excluded.name, native=excluded.native, grp=excluded.grp, font=excluded.font, sort=excluded.sort;
delete from scriptura_app_characters where language_id='chinese';
delete from scriptura_app_vowels where language_id='chinese';
delete from scriptura_app_units where language_id='chinese';
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('chinese_numbers','chinese','Numbers','一 – 十','practice',0,NULL,NULL);
insert into scriptura_app_units (id,language_id,title,subtitle,accent,sort,slots,concept) values ('chinese_nature','chinese','Nature & body','大 – 木','indic',1,NULL,NULL);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',0,'一','yī','yī','one','',0,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',1,'二','èr','èr','two','',1,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',2,'三','sān','sān','three','',2,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',3,'四','sì','sì','four','',3,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',4,'五','wǔ','wǔ','five','',4,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',5,'六','liù','liù','six','',5,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',6,'七','qī','qī','seven','',6,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',7,'八','bā','bā','eight','',7,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',8,'九','jiǔ','jiǔ','nine','',8,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_numbers',9,'十','shí','shí','ten','',9,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',10,'大','dà','dà','big','',10,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',11,'小','xiǎo','xiǎo','small','',11,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',12,'人','rén','rén','person','',12,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',13,'口','kǒu','kǒu','mouth','',13,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',14,'日','rì','rì','sun','',14,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',15,'月','yuè','yuè','moon','',15,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',16,'山','shān','shān','mountain','',16,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',17,'水','shuǐ','shuǐ','water','',17,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',18,'火','huǒ','huǒ','fire','',18,false);
insert into scriptura_app_characters (language_id,unit_id,char_index,char,roman,name,gloss,cognate,sort,no_vowel_sign) values ('chinese','chinese_nature',19,'木','mù','mù','wood','',19,false);

commit;
